// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Raktarkezelo.Data;

#nullable disable

namespace Raktarkezelo.Migrations
{
    [DbContext(typeof(RaktarDb))]
    [Migration("20260326172311_tablasdi")]
    partial class tablasdi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Raktarkezelo.Models.Entities.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Üdítő",
                            MinStock = 10,
                            Name = "Coca-Cola 0.5L",
                            Note = "",
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Üdítő",
                            MinStock = 10,
                            Name = "Fanta 0.5L",
                            Note = "",
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Üdítő",
                            MinStock = 15,
                            Name = "Ásványvíz 1.5L",
                            Note = "",
                            Stock = 60
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Írószer",
                            MinStock = 20,
                            Name = "Golyóstoll kék",
                            Note = "",
                            Stock = 100
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Írószer",
                            MinStock = 20,
                            Name = "Ceruza HB",
                            Note = "",
                            Stock = 80
                        },
                        new
                        {
                            ProductId = 6,
                            Category = "Írószer",
                            MinStock = 10,
                            Name = "A4 füzet",
                            Note = "",
                            Stock = 35
                        },
                        new
                        {
                            ProductId = 7,
                            Category = "Háztartás",
                            MinStock = 8,
                            Name = "Toalettpapír",
                            Note = "",
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 8,
                            Category = "Háztartás",
                            MinStock = 6,
                            Name = "Papírtörlő",
                            Note = "",
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 9,
                            Category = "Háztartás",
                            MinStock = 5,
                            Name = "Mosogatószer",
                            Note = "",
                            Stock = 18
                        },
                        new
                        {
                            ProductId = 10,
                            Category = "Egészségügy",
                            MinStock = 10,
                            Name = "Sebtapasz",
                            Note = "",
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 11,
                            Category = "Egészségügy",
                            MinStock = 8,
                            Name = "Kézfertőtlenítő",
                            Note = "",
                            Stock = 22
                        },
                        new
                        {
                            ProductId = 12,
                            Category = "Egészségügy",
                            MinStock = 25,
                            Name = "Maszk",
                            Note = "",
                            Stock = 100
                        },
                        new
                        {
                            ProductId = 13,
                            Category = "Elektronika",
                            MinStock = 12,
                            Name = "Elem AA",
                            Note = "",
                            Stock = 45
                        },
                        new
                        {
                            ProductId = 14,
                            Category = "Elektronika",
                            MinStock = 8,
                            Name = "USB kábel",
                            Note = "",
                            Stock = 28
                        },
                        new
                        {
                            ProductId = 15,
                            Category = "Elektronika",
                            MinStock = 4,
                            Name = "Hosszabbító",
                            Note = "",
                            Stock = 12
                        });
                });

            modelBuilder.Entity("Raktarkezelo.Models.Entities.StockTransactions", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("StockTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_StockTransactions_Type", "[Type] IN ('IN','OUT','ADJUST')");
                        });
                });

            modelBuilder.Entity("Raktarkezelo.Models.Entities.Userinfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Userinfo");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Email = "admin@raktar.hu",
                            IsActive = true,
                            Passwordhash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 1,
                            Email = "manager@raktar.hu",
                            IsActive = true,
                            Passwordhash = "hmSFeWz6jXwM9xEWQCBbgwdkM1R1d1EdgfgDCumezqU=",
                            Role = 2,
                            Username = "manager"
                        });
                });

            modelBuilder.Entity("Raktarkezelo.Models.Entities.StockTransactions", b =>
                {
                    b.HasOne("Raktarkezelo.Models.Entities.Products", "Product")
                        .WithMany("StockTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Raktarkezelo.Models.Entities.Userinfo", "User")
                        .WithMany("StockTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Raktarkezelo.Models.Entities.Products", b =>
                {
                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("Raktarkezelo.Models.Entities.Userinfo", b =>
                {
                    b.Navigation("StockTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
